# Generated by Django 3.2.9 on 2021-11-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211130_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='tilte',
            new_name='title',
        ),
    ]
