# Generated by Django 3.2.9 on 2021-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_tilte_auction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='photo_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
