# Generated by Django 3.2.9 on 2021-12-01 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ManyToManyField(related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
